version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aquasdr-backend
    restart: always
    ports:
      - "6002:6002"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
