import test from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {createServer} from 'node:net';
import {mkdtemp} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {randomUUID} from 'node:crypto';
import {WebSocket} from 'ws';
const pause=ms=>new Promise(r=>setTimeout(r,ms));
async function until(check,ms=6000){const start=Date.now();while(!check()){if(Date.now()-start>ms)throw new Error('Timed out waiting for API state');await pause(20);}}
test('browser bridge: apply, output, preview, recording, playback and lease loss',async()=>{
 const probe=createServer();await new Promise(r=>probe.listen(0,'127.0.0.1',r));const port=probe.address().port;await new Promise(r=>probe.close(r));
 const directory=await mkdtemp(join(tmpdir(),'aquasdr-api-'));
 const child=spawn(process.execPath,['server/index.js'],{env:{...process.env,PORT:String(port),AQUASDR_DATA_DIR:directory},stdio:['ignore','pipe','pipe']});
 let started=false,logs='',socket,timer,state;
 child.stdout.on('data',s=>{logs+=s;started=logs.includes('AquaSDR bridge')});child.stderr.on('data',s=>logs+=s);
 const client=randomUUID();
 const post=async(path,body={})=>{const r=await fetch(`http://127.0.0.1:${port}/api/${path}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,client})});return {status:r.status,body:await r.json()}};
 try{
  await until(()=>started);socket=new WebSocket(`ws://127.0.0.1:${port}/ws/telemetry`);
  socket.on('message',s=>state=JSON.parse(s));await new Promise(r=>socket.once('open',r));
  const beat=()=>socket.readyState===1&&socket.send(JSON.stringify({type:'controlHeartbeat',client}));beat();timer=setInterval(beat,250);
  await until(()=>state?.transmitter?.ready);
  await until(()=>state?.referencePreview?.digitalChecks);
  assert.equal(state.current.control.outputEnabled,false);
  assert.equal(state.current.control.hasApplied,false);
  assert.equal(state.current.preview,undefined);
  assert.equal(state.current.batteryScenario.source,'scenario');
  assert(!Number.isFinite(state.current.power.soc));assert.equal(state.current.powerEstimate.soc,null);
  assert.equal(state.referencePreview.purpose,'CONFIGURATION_INSPECTION');
  assert.equal(state.referencePreview.tx.provenance,'CALCULATED_C_REFERENCE');
  assert(state.referencePreview.digitalChecks.samples>0);
  assert.equal(state.operational.target,'COMPUTED');assert.equal(state.operational.commandReady,true);
  assert.equal((await post('transmitter',{op:'start',target:'STM32'})).status,409);
  assert.equal((await post('transmitter',{op:'ping'})).status,200);
  assert.equal((await post('transmitter',{op:'get_waveform'})).status,200);
  assert.equal((await post('transmitter',{op:'source',source:'WEB_COMMAND'})).status,200);
  assert.equal((await post('environment',{turbidityIndex:101,depth:3,temperature:26})).status,400);
  assert.equal((await post('environment',{profile:'UNKNOWN'})).status,400);
  assert.equal((await post('environment',{profile:'CLEAR_SHALLOW_REEF',depth:3})).status,400);
  assert.equal((await post('environment',{profile:'CLEAR_SHALLOW_REEF'})).status,200);
  await until(()=>state.current.control.qualified);
  await until(()=>state.referencePreview?.config.frequency===42);
  assert.equal(state.current.control.outputEnabled,false);
  assert.equal(state.current.control.hasApplied,false);
  assert.equal((await post('transmitter',{op:'start'})).status,200);
  await until(()=>state.current.waveform?.frequency===42 && state.current.preview?.tx);
  assert.equal(state.current.samples,undefined);assert.equal(state.current.power.watts,null);
  assert.equal(state.current.firmwareMode,'ADAPTIVE_TRANSMITTER');assert.equal(state.current.applicationAck.profile,'CLEAR_SHALLOW_REEF');
  assert.equal((await post('transmitter',{op:'status'})).status,200);
  assert.equal((await post('control',{action:'record'})).status,200);await pause(550);
  assert(state.history.some(h=>h.environment?.source==='WEB_COMMAND' && h.environment.turbidityIndex===12));
  assert(state.history.every(h=>h.sensors.turbidity===null));
  assert(state.history.some(h=>h.batteryScenario?.source==='scenario' && !Number.isFinite(h.power.soc)));
  await post('environment',{turbidityIndex:10,depth:80,temperature:10});
  await until(()=>state.current.waveform?.frequency===38 && state.current.preview?.config.frequency===38);
  assert.equal(state.current.waveform.pulse,8);
  for(const mode of ['GEOMETRIC SWEEP','PHASE-CODED PULSE']){
    assert.equal((await post('transmitter',{op:'waveform',mode,window:'BLACKMAN'})).status,200);
    await until(()=>state.current.waveform?.mode===mode);
  }
  await post('transmitter',{op:'stop'});await until(()=>!state.current.control.outputEnabled);
  const saved=await post('save');assert(saved.body.samples>0);
  const record=await (await fetch(`http://127.0.0.1:${port}/api/sessions/${saved.body.sessionId}`)).json();
  assert(record.samples.some(s=>s.preview?.tx && s.environment?.source==='WEB_COMMAND'));
  assert(record.samples.some(s=>s.batteryScenario?.source==='scenario' && !Number.isFinite(s.power.soc)));
  assert(record.samples.some(s=>s.applicationAck?.profile==='DEEP_OPEN_WATER' && s.firmwareMode==='ADAPTIVE_TRANSMITTER'));
  await post('mode',{mode:'playback',sessionId:saved.body.sessionId});await until(()=>state.mode==='playback');
  assert(state.history.some(h=>h.environment?.source==='WEB_COMMAND'));
  assert(state.current.batteryScenario?.source==='scenario');
  assert.equal((await post('transmitter',{op:'start'})).status,409);assert.equal((await post('environment',{turbidityIndex:12,depth:3,temperature:26})).status,409);
  await post('mode',{mode:'demo'});await until(()=>state.mode==='demo');
  await post('environment',{turbidityIndex:12,depth:3,temperature:26});await until(()=>state.current.control.qualified);
  await post('transmitter',{op:'start'});await until(()=>state.current.control.outputEnabled);
  clearInterval(timer);socket.close();
  let stopped;const stopDeadline=Date.now()+1200;
  do {await pause(30);stopped=await (await fetch(`http://127.0.0.1:${port}/api/system`)).json();} while(stopped.current.control.outputEnabled && Date.now()<stopDeadline);
  assert.equal(stopped.current.control.outputEnabled,false);assert.equal(stopped.current.control.reason,'OUTPUT_DISABLED');
  await pause(2600);
  const final=await (await fetch(`http://127.0.0.1:${port}/api/system`)).json();assert.equal(final.current.control.reason,'WEB_LEASE_EXPIRED');assert.equal(final.current.control.outputEnabled,false);
 }finally{clearInterval(timer);socket?.terminate();child.kill('SIGTERM');}
});
