#!/usr/bin/env python3
"""Fit and printability check for the payload pod. Reads params.json, writes params.scad, prints PASS/FAIL per check.
Pure geometry on the numbers in params.json; it cannot know whether those numbers match your real parts."""
import json, math, pathlib, sys
here = pathlib.Path(__file__).parent
P = json.loads((here / "params.json").read_text())
t, c, d = P["tube"], P["cap"], P["deck"]
R_out = t["od"] / 2; R_in = R_out - t["wall"]; ID = 2 * R_in
# deck layout along the axis
deck_l = d["end_margin"] * 2 + P["nucleo"]["l"] + d["gap_between_boards"] + P["afe"]["l"]
deck_w = ID - 2 * d["side_clearance"] - 2 * 0  # spans between the rails' inner faces + rests on them
inner_clear = t["length"] - 2 * c["spigot_depth"]
checks = []
def chk(name, ok, detail, slack=None): checks.append((name, bool(ok), detail, slack))
chord = lambda y: 2 * math.sqrt(max(0.0, R_in ** 2 - y ** 2))  # full width of the bore at height y
# deck at y = 0 .. -thickness; boards above (positive y), battery below (negative y)
chk("deck fits between end caps", deck_l + 2 * d["end_clearance"] <= inner_clear, f"deck {deck_l:.1f} mm + 2x{d['end_clearance']} clearance vs {inner_clear:.1f} mm clear inside")
for key in ("nucleo", "afe"):
    b = P[key]; top = d["thickness"] * 0 + b["standoff"] + b["height_with_headers" if key == "nucleo" else "height"]
    half = b["w"] / 2 + 2  # board edge + margin
    avail = math.sqrt(max(0.0, R_in ** 2 - half ** 2))
    chk(f"{key} width fits the deck", b["w"] + 2 * 3 <= deck_w, f"board {b['w']} mm + 3 mm margins vs deck {deck_w:.1f} mm")
    chk(f"{key} height clears the bore at its edges", top + 1 <= avail, f"needs {top + 1:.1f} mm above the deck, bore allows {avail:.1f} mm at x = +-{half:.0f} mm")
bat = P["battery"]
need_down = d["thickness"] + d["rail_height"] * 0 + bat["h"]
avail_down = math.sqrt(max(0.0, R_in ** 2 - (bat["w"] / 2 + 1) ** 2))
chk("battery width fits between the rails", bat["w"] + 2 <= ID - 2 * d["rail_depth"], f"pack {bat['w']} mm vs {ID - 2 * d['rail_depth']:.1f} mm between rails")
chk("battery height clears the bore below the deck", need_down + 2 <= avail_down, f"needs {need_down + 2:.1f} mm below the top of the deck, bore allows {avail_down:.1f} mm at its edges", avail_down - (need_down + 2))
chk("battery length fits the deck", bat["l"] + 2 * d["end_margin"] <= deck_l, f"pack {bat['l']} mm vs deck {deck_l:.1f} mm")
chk("longest printed part fits the bed", max(t["length"], t["od"]) <= P["print"]["bed_mm"], f"tube {t['length']} mm long, {t['od']} mm OD vs {P['print']['bed_mm']} mm bed")
chk("oring groove leaves wall in the cap spigot", c["spigot_wall"] - 2.4 >= 1.2, f"{c['spigot_wall']} mm wall minus a 2.4 mm groove")
chk("tube wall can take radial M3 screws", t["wall"] >= 3, f"wall {t['wall']} mm")
chk("cap holes stay on the 116 mm disc", all(math.hypot(*c2) + 6 <= R_out for c2 in [P["caps"]["a"]["usb_offset"], P["caps"]["a"]["bnc_offset"], P["caps"]["a"]["switch_offset"], P["caps"]["b"]["pot_offset"], P["caps"]["b"]["gland_offset"], *P["caps"]["b"]["post_offsets"]]), "all feature centres inside the flange with 6 mm edge margin")
unconfirmed = [k for k in ("tube", "afe", "battery") if not P[k].get("confirmed")]
b = P["battery"]; c0 = b["cell"]
derived = (round(b["series"] * c0["d"] + 2 * b["wrap"], 1), round(b["parallel"] * c0["d"] + 2 * b["wrap"], 1), round(c0["l"] + b["bms_extra_l"] + 2 * b["wrap"], 1))
chk("battery envelope matches the 3S2P 18650 derivation", (b["w"], b["h"], b["l"]) == derived, f"w {b['w']} x h {b['h']} x l {b['l']} mm from {b['series']}S{b['parallel']}P cells of {c0['d']} x {c0['l']} mm")
ok = all(x[1] for x in checks)
for name, passed, detail, slack in checks:
    tight = " (TIGHT: measure the real part)" if slack is not None and passed and slack < 3 else ""
    print(f"{'PASS' if passed else 'FAIL'}  {name}: {detail}" + (f"; slack {slack:.1f} mm{tight}" if slack is not None else ""))
print(f"\nUNCONFIRMED DIMENSIONS (measure before printing): {', '.join(unconfirmed) or 'none'}")
print("MEASURE WITH CALIPERS: (1) inner bore of the acrylic hull (the 116 mm pod needs a bore of at least 117 mm; the model assumes 174 mm), (2) the battery pack W x L x H including wrap and leads (it clears the bore by only the slack shown above), (3) the analog board you actually build, (4) the Nucleo height with your headers, (5) the connector bodies for the cap holes.")
print("READY TO PRINT: " + ("yes" if not unconfirmed and ok else "NO (the checks pass on the stated numbers only; the unconfirmed dimensions above are not measurements)"))
# Emit params.scad for pod.scad
scad = [f"// Generated by check_fit.py from params.json: do not edit by hand.",
        f"tube_od={t['od']}; tube_wall={t['wall']}; tube_len={t['length']};",
        f"cap_flange={c['flange_t']}; spig_depth={c['spigot_depth']}; spig_wall={c['spigot_wall']}; oring={c['oring_cord']}; fit={c['fit_clearance']};",
        f"screw_clear={c['screw_clear_d']}; screw_pilot={c['screw_pilot_d']}; n_screws={c['screws_per_cap']};",
        f"deck_t={d['thickness']}; deck_len={deck_l:.2f}; deck_w={deck_w:.2f}; rail_d={d['rail_depth']}; rail_h={d['rail_height']}; zip_w={d['zip_slot'][0]}; zip_t={d['zip_slot'][1]};",
        f"nuc_w={P['nucleo']['w']}; nuc_l={P['nucleo']['l']}; nuc_so={P['nucleo']['standoff']};",
        f"afe_w={P['afe']['w']}; afe_l={P['afe']['l']}; afe_so={P['afe']['standoff']}; board_gap={d['gap_between_boards']}; end_margin={d['end_margin']};",
        f"bat_w={P['battery']['w']}; bat_l={P['battery']['l']}; bat_h={P['battery']['h']};",
        f"usb_slot={P['caps']['a']['usb_slot']}; usb_off={P['caps']['a']['usb_offset']}; bnc_d={P['caps']['a']['bnc_d']}; bnc_off={P['caps']['a']['bnc_offset']}; sw_d={P['caps']['a']['switch_d']}; sw_off={P['caps']['a']['switch_offset']};",
        f"pot_d={P['caps']['b']['pot_d']}; pot_off={P['caps']['b']['pot_offset']}; post_d={P['caps']['b']['post_d']}; post_offs={P['caps']['b']['post_offsets']}; gland_d={P['caps']['b']['gland_d']}; gland_off={P['caps']['b']['gland_offset']};"]
(here / "params.scad").write_text("\n".join(scad) + "\n")
sys.exit(0 if ok else 1)
