// Generated by check_fit.py from params.json: do not edit by hand.
tube_od=116; tube_wall=3; tube_len=184;
cap_flange=4; spig_depth=10; spig_wall=4; oring=3.0; fit=0.3;
screw_clear=3.4; screw_pilot=2.6; n_screws=4;
deck_t=3; deck_len=150.50; deck_w=108.00; rail_d=5; rail_h=5; zip_w=3.2; zip_t=1.6;
nuc_w=70.0; nuc_l=82.5; nuc_so=6;
afe_w=60.0; afe_l=40.0; afe_so=6; board_gap=12; end_margin=8;
bat_w=57.8; bat_l=72.2; bat_h=39.2;
usb_slot=[14.0, 8.0]; usb_off=[0, -30]; bnc_d=9.7; bnc_off=[-28, 12]; sw_d=6.2; sw_off=[28, 12];
pot_d=7.2; pot_off=[0, 18]; post_d=4.2; post_offs=[[-22, -22], [22, -22]]; gland_d=8.0; gland_off=[0, -34];
