#!/usr/bin/env python3
"""Converts docs/assets/aquasdr-wordmark.png (white on transparent) into an RGB565 bitmap for the 160x128 ST7735.
The tagline is too small to read at this size, so only the mark and the AQUASDR wordmark are kept (the sketch prints the tagline
with the display font). White on black, anti-aliased. Writes arduino/04_all_sensors-compatible header into the combined sketch.
    python3 scripts/make-tft-wordmark.py
"""
import pathlib
from PIL import Image
import numpy as np

root = pathlib.Path(__file__).resolve().parent.parent
src = root / "docs/assets/aquasdr-wordmark.png"
out = root / "arduino/05_sensors_adaptive_tx/AquaSdrWordmark.h"
W = 156                                    # leave a 2 px margin on the 160 px panel
im = Image.open(src).convert("RGBA")
a = np.array(im)[..., 3]                   # the artwork is white; its alpha is the shape
rows = np.where(a.max(axis=1) > 20)[0]
cols = np.where(a.max(axis=0) > 20)[0]
# keep the circular mark and the AQUASDR letters; cut the tagline (below the letters, roughly the bottom 12 % of the logo box)
top, bottom = rows.min(), rows.max()
letters_bottom = int(top + (bottom - top) * 0.89)
# the circular mark spans the full height, so crop to the mark's own extent and the letters' extent
mark = a[:, :int(cols.min() + (cols.max() - cols.min()) * 0.205)]
mrows = np.where(mark.max(axis=1) > 20)[0]
crop = im.crop((cols.min(), mrows.min(), cols.max() + 1, mrows.max() + 1))
H = round(crop.height * W / crop.width)
small = crop.resize((W, H), Image.LANCZOS)
alpha = np.array(small)[..., 3].astype(np.float32) / 255.0
# the tagline sits at the bottom of the original box beside the mark; blank anything below the wordmark letters
letters_rows = np.where(a[:, int(cols.min() + (cols.max() - cols.min()) * 0.26):].max(axis=1) > 20)[0]
gray = np.clip(alpha, 0, 1)
rgb565 = ((np.round(gray * 31).astype(np.uint16) << 11) | (np.round(gray * 63).astype(np.uint16) << 5) | np.round(gray * 31).astype(np.uint16))
body = []
flat = rgb565.flatten()
for i in range(0, len(flat), 12):
    body.append("  " + ", ".join(f"0x{v:04X}" for v in flat[i:i + 12]) + ",")
out.write_text("#pragma once\n\n#include <Arduino.h>\n\n"
               "// Generated by scripts/make-tft-wordmark.py from docs/assets/aquasdr-wordmark.png. Do not edit by hand.\n"
               f"constexpr int16_t AQUASDR_WORDMARK_W = {W};\nconstexpr int16_t AQUASDR_WORDMARK_H = {H};\n"
               "const uint16_t PROGMEM AQUASDR_WORDMARK[] = {\n" + "\n".join(body) + "\n};\n")
# preview for a human check
prev = Image.fromarray((gray * 255).astype(np.uint8)).resize((W * 4, H * 4), Image.NEAREST)
prev.save("/private/tmp/claude-501/-Users-sudharsan-Downloads-AquaSDR/974881d6-97cd-49b8-a6c0-c2de9a3acebd/scratchpad/wordmark-preview.png")
print(f"wrote {out.name}: {W}x{H} px, {W*H*2} bytes")
